#!/usr/bin/env python3
"""
aprag.mcp — MCP server for the AP-RAG academic-papers knowledge base.

Thin stdio MCP server that forwards to the AP-RAG query server (LightRAG + Qdrant +
embeddings + an answer LLM). Holds no models and no data; it just shapes two tools
over `aprag.client`.

Server selection: $APRAG_QUERY_URL (default http://localhost:8001). Point it at your
deployment, e.g. register with `--env APRAG_QUERY_URL=http://<host>:8001`.

Register (after `pip install .` puts `aprag-mcp` on PATH):
    claude mcp add --scope user aprag \\
        --env APRAG_QUERY_URL=http://<host>:8001 -- aprag-mcp
"""

from __future__ import annotations

import logging
import sys

# All diagnostics go to stderr; stdout is reserved for JSON-RPC on a stdio server.
# basicConfig must run before importing mcp so any import-time logs land on stderr.
logging.basicConfig(stream=sys.stderr, level=logging.WARNING)

from mcp.server.fastmcp import FastMCP  # noqa: E402

from . import client  # noqa: E402
from .client import APRAGError  # noqa: E402

mcp = FastMCP("aprag")


def _format_retrieval(result: dict) -> str:
    """Render structured retrieval as readable text for the orchestrating agent."""
    if result.get("status") != "success":
        return (
            f"No results (status={result.get('status')}): "
            f"{result.get('message', 'no data returned')}"
        )

    data = result.get("data") or {}
    meta = result.get("metadata") or {}
    chunks = data.get("chunks") or []
    entities = data.get("entities") or []
    relationships = data.get("relationships") or []

    lines: list[str] = [f"Retrieved {len(chunks)} chunk(s) in mode={meta.get('query_mode', '?')}."]

    for i, ch in enumerate(chunks, 1):
        lines.append(
            f"\n[chunk {i}] ref={ch.get('reference_id', '?')} "
            f"source={ch.get('file_path', 'unknown')}"
        )
        lines.append((ch.get("content") or "").strip())

    if entities:
        lines.append(f"\n--- Entities ({len(entities)}) — follow these for the next hop ---")
        for e in entities:
            lines.append(
                f"- {e.get('entity_name', '?')} [{e.get('entity_type', '?')}]: "
                f"{(e.get('description') or '').strip()}"
            )

    if relationships:
        lines.append(f"\n--- Relationships ({len(relationships)}) ---")
        for r in relationships:
            lines.append(
                f"- {r.get('src_id', '?')} -> {r.get('tgt_id', '?')}: "
                f"{(r.get('description') or '').strip()}"
            )

    return "\n".join(lines)


@mcp.tool()
async def aprag_query(question: str, mode: str = "hybrid") -> str:
    """
    Answer a research question from the AP-RAG knowledge base (synthesized answer).

    Returns a written, citation-bearing answer generated by an LLM over the retrieved
    context. Use this when you want a finished answer rather than raw evidence.

    For iterative/agentic retrieval where you want to read the underlying passages and
    decide what to search next, use `aprag_retrieve` instead.

    Args:
        question: The research question.
        mode: Retrieval strategy —
            "hybrid" (default): entity- + theme-focused, good general choice.
            "local": specific entity/paper questions.
            "global": broad cross-paper themes and trends.
            "mix": knowledge graph + vector search combined.
            "naive": plain vector search, fastest, no graph reasoning.
    """
    try:
        return await client.query(question, mode=mode)
    except APRAGError as exc:
        return f"Query failed: {exc}"


@mcp.tool()
async def aprag_retrieve(
    question: str,
    mode: str = "naive",
    top_k: int | None = None,
    chunk_top_k: int | None = None,
) -> str:
    """
    Retrieve raw evidence from the AP-RAG knowledge base — NO answer synthesis.

    Returns the underlying text chunks (and, in graph modes, the entities and
    relationships) that retrieval surfaced. This is the primitive for agentic
    multi-hop retrieval: read the chunks, pick a lead from the chunks/entities, then
    call again with a refined question and/or a different mode.

    Calls are stateless — each call retrieves independently. YOU accumulate and
    deduplicate evidence across hops; the server does not remember prior calls.

    Args:
        question: The retrieval query for this hop.
        mode: Retrieval strategy —
            "naive" (default): plain vector search; returns chunks only (no graph).
            "local": entities + their chunks (specific entity/paper leads).
            "global": relationships + connected entities (broad themes).
            "hybrid"/"mix": combined graph + vector retrieval.
        top_k: KG entities/relations to retrieve (server default if omitted).
        chunk_top_k: text chunks to keep after reranking (server default if omitted).
    """
    try:
        result = await client.retrieve(
            question, mode=mode, top_k=top_k, chunk_top_k=chunk_top_k
        )
        return _format_retrieval(result)
    except APRAGError as exc:
        return f"Retrieval failed: {exc}"


def main() -> None:
    """Console-script entry point (`aprag-mcp`)."""
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
